SELECT DISTINCT ?genitive WHERE { 

   { <URI> <http://lemon-model.net/lemon#canonicalForm> ?form . }
   UNION
   { <URI> <http://lemon-model.net/lemon#otherForm> ?form . } 

   ?form <http://www.lexinfo.net/ontology/2.0/lexinfo#number> <http://www.lexinfo.net/ontology/2.0/lexinfo#singular> .  
   ?form <http://www.lexinfo.net/ontology/2.0/lexinfo#case> <http://www.lexinfo.net/ontology/2.0/lexinfo#genitiveCase> .  
   ?form <http://lemon-model.net/lemon#writtenRep> ?genitive .  
}
